### ISSUE TITLE
Kibana: Unknown error while connecting to Elasticsearch

### ISSUE THREAD

**Issue by radiumx3** [stackbuilder/dockerfiles#1]
Kibana: Unknown error while connecting to Elasticsearch

after setting my kibana alias in your config file this is the error it throws me when i try to access to kibana, could you provide more info about what s in your elasticsearch.yml (or share your elastic repo if it^s not too much to ask)

**Comment by stackbuilder** [comment]
I use the Docker supported Elasticsearch image.

docker run -d --name es elasticsearch 
#start the kibana interface
docker run -d --name kibana --link es:es -p 5601:5601 --name kibana hfranzen/kibana

**Comment by radiumx3** [comment]
Fixed, it was a mess with proxy settings from the company, which is an issue referenced in kibana repo allready.
